### ISSUE TITLE
PDF Preview Area too Small

### ISSUE THREAD

**Issue by SigmaX** [masonpublishing/OJS-Theme#1]
On Chrome and Mac OS X (and perhaps others), when you click on the "PDF" link to view an article, the PDF viewer box's height is very small compared to the rest of the page.

Example: http://journals.gmu.edu/jmgr/article/view/533/1082

![screen shot 2015-10-03 at 1 26 40 pm](https://cloud.githubusercontent.com/assets/313154/10264154/7a3ff3a2-69d2-11e5-9858-802ed4d5af81.png)

**Comment by jerielizabeth** [comment]
Definitely too small! It is a little better using the pdf.js plugin viewer (in the list at /manager/plugins/generic) but I have a style fix that I'll push up that makes it bigger. Thanks!
