### ISSUE TITLE
Blank screen after installation

### ISSUE THREAD

**Issue by amirdarajeh** [masonpublishing/OJS-Theme#2]
Hi
first thanks for sharing this template with us.
I downloaded your codes and installed it on my OJS, But after selecting your theme, in "The Look" I see a blank screen!!
I tested on OJS 2.4.6 and 2.4.8
Please help to resolve this issue

Regards
Amir

**Comment by jerielizabeth** [comment]
Hi Amir,
Thank you for letting me know! My guess is because of the name of the theme folder -- I forgot to mention in the README (and have now corrected that) that the folder must be named `mpg` for the theme to install properly. 

Does it load if you make that correction?

**Comment by amirdarajeh** [comment]
Hi
Thanks for your very quick respond.
It's works finely after changing folder name, But it didn't work with OJS 2.4.8, I tested with OJS 2.4.6.
And I found another issue when I clicked on "Home", I got internal server error. http://ojs247.gmj.ir/
All Pages work finely expect "Home".
http://ojs247.gmj.ir/index.php/rtias/about

## Could you help me to make your template compatible with OJS 2.4.8?

Thanks in advance
Amir

**Comment by jerielizabeth** [comment]
Hmm... that sounds like a different / larger problem. I will try to take a look at it tomorrow. Thank you for the heads-up!

**Comment by jerielizabeth** [comment]
Hi Amir,

So we are running the theme on OJS 2.4.8 and have had no problems. Any chance something went odd in your config file or with your server?

**Comment by amirdarajeh** [comment]
Hi Elizabeth
Thanks for your respond

## You are right, It's work finely, Thanks for this great contribution

Good Luck
Amir
