### ISSUE TITLE
Problem loading print.css and screen.css

### ISSUE THREAD

**Issue by leoto17** [masonpublishing/OJS-Theme#4]
There are three issues in file templates/common/head.tpl, in lines 14, 21 and 22 the variable $baseURL is incorrect, the correct variable is $baseUrl

**Comment by davidalar** [comment]
Hi @leoto17 ... thanks for the info.
Can you help me with this?
Have you tried to login from mobile devices?
I installed the Theme Mason Several times and it works perfect. but I can not login from mobile devices...

Could you help me in solving esta problem?

Thank you very much!

**Comment by jerielizabeth** [comment]
Thank you, @leoto17! That explains a problem that I was having moving between my localhost and the server.
